### ISSUE TITLE
Component not working anymore

### ISSUE THREAD

**Issue by hanneshier** [T3m3z/HA-Vestel-Component#4]
The component is not working anymore. I tried to fix the errors from the HomeAssistant console, but its still not working. If anyone is interested in further investigating, here is my fork: [https://github.com/hanneshier/HA-Vestel-Component?tab](https://github.com/hanneshier/HA-Vestel-Component?)

**Comment by T3m3z** [comment]
Hello! The problem seems to be that previously working pyvesteltv library (and more specifically SSDP discovery) does not work correctly anymore with the newest Home Assistant versions.

I decided to write new code which uses only TCP port 1986 to communicate with TV and detect whether it is turned on. It keeps things relatively simple as it removes SSDP, some HTTP requests and Websockets but also removes some functionality (ability to start/stop Netflix/Youtube for example).

Please see code here: https://github.com/T3m3z/HA-Vestel-Component/tree/master/custom_components/vestel2

Example of minimal configuration:
```yaml
media_player:
  - platform: vestel2
    host: 192.168.0.100
    name: "Procaster"
    use_headphone_volume: false #Set to true if using headphone output
    sources: #These need to be in same order as in TV. Switch sources on TV, check values from HA entity and add them here.
      - TV
      - HDMI1
      - HDMI2
      - HDMI3
      - VGA/PC
```
